version: '3'
services:
  angular:
    build:
      context: ./src/app
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    container_name: localhost
    volumes:
       - ./app:/usr/app
       - /usr/src/app/node_modules
